services:
  waka3x:
    build: .
    init: true
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      # See README.md and config.default.yml for all config options
      WAKA3X_DB_TYPE: "postgres"
      WAKA3X_DB_NAME: "waka3x"
      WAKA3X_DB_USER: "waka3x"
      WAKA3X_DB_HOST: "db"
      WAKA3X_DB_PORT: "5432"
      WAKA3X_DB_PASSWORD_FILE: "/run/secrets/db_password"       # alternatively, set WAKA3X_DB_PASSWORD directly without the use of secrets
      WAKA3X_PASSWORD_SALT_FILE: "/run/secrets/password_salt"   # alternatively, set WAKA3X_PASSWORD_SALT directly without the use of secrets
      WAKA3X_MAIL_SMTP_PASS_FILE: "/run/secrets/smtp_pass"      # alternatively, set WAKA3X_MAIL_SMTP_PASS directly without the use of secrets
    secrets:
      - source: password_salt
        target: password_salt
        uid: '1000'
        gid: '1000'
        mode: '0400'

      - source: smtp_pass
        target: smtp_pass
        uid: '1000'
        gid: '1000'
        mode: '0400'

      - source: db_password
        target: db_password
        uid: '1000'
        gid: '1000'
        mode: '0400'

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "waka3x"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"        # alternatively, set POSTGRES_PASSWORD directly without the use of secrets
      POSTGRES_DB: "waka3x"
    volumes:
      - waka3x-db-data:/var/lib/postgresql/data
    secrets:
      - db_password

# secrets can be defined either from a local file or from an environment variable defined on the client host (the one that runs `docker compose` command)
# see https://docs.docker.com/compose/how-tos/use-secrets/ for details
secrets:
  password_salt:
    environment: WAKA3X_PASSWORD_SALT
  smtp_pass:
    environment: WAKA3X_MAIL_SMTP_PASS
  db_password:
    environment: WAKA3X_DB_PASSWORD

volumes:
  waka3x-db-data: {}
